#!/bin/sh
cd /boot/home/projects/TinyTim/PackagingFolder
package create -b TinyTim_0.1-6_gcc2.hpkg
sleep 0.5
package add TinyTim_0.1-6_gcc2.hpkg data apps bin
sleep 0.5
addattr BeShare:Info "GUI frontend to the TinyURL URL-shortening utility" TinyTim_0.1-6_gcc2.hpkg
becopy TinyTim_0.1-6_gcc2.hpkg "/Storage/Haiku/My ports"
mv TinyTim_0.1-6_gcc2.hpkg /boot/home/projects/repo

